### ISSUE TITLE
Some remarks on the GitHub Actions workflow

### ISSUE THREAD

**Issue by bedroesb** [BioSchemas/specifications#627]
Hello, I had some comments when going through the workflow file. I think it can be shortened a lot.

- I see that @sahar-frikha you are using a personal GitHub token, I don't think this is future proof, what if you go out of the project? Either we make use of the default GitHub token, or we create a new user account that is neutral.
- ```
      - name: Checkout Spec Repo and Retreive the Preceding Commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v21

      - name: List Changed Files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

  ```
  Why is the preceding commit taken and the differences displayed I guess you just want to work with the latest state of the repo? 
- ```
      - name: Checkout the DDE repo
        env:
          GITHUB_TOKEN: ${{ secrets.Sahar_Workflows_Token }}
        run: | 
          git clone https://user:$GITHUB_TOKEN@github.com/BioSchemas/bioschemas-dde
          cd bioschemas-dde 
          git checkout main
          ls
  ```
  This can easily be replaced by
  ```
      - name: Checkout the DDE repo
        uses: actions/checkout@v3
        with:
          repository: BioSchemas/bioschemas-dde
          path: bioschemas-dde
          ref: main
  ```
  This saves a lot of time since it gets mounted. Same for the `Checkout the Website repo` step
- I would use this action: https://github.com/marketplace/actions/git-auto-commit to create your commits, it can create also the new branch, this will reduce the code a lot. You can than also specify from which repo you make this commit.
